###
GET http://1.117.72.139/XPJarvef6GxRdtdc/hello3

###
GET http://1.117.72.139/XPJarvef6GxRdtdc/workers/

###
GET http://1.117.72.139/XPJarvef6GxRdtdc/tasks/

###
POST http://1.117.72.139/XPJarvef6GxRdtdc/workers/local-2/heartbeat

###
POST http://1.117.72.139/XPJarvef6GxRdtdc/workers
Content-Type: application/json

{
    "id": "local-1",
    "runtime_type": "cpu"
}

###
POST http://1.117.72.139/XPJarvef6GxRdtdc/tasks
Content-Type: application/json

{
    "id": "local-1",
    "runtime_type": "cpu"
}

###
POST http://1.117.72.139/XPJarvef6GxRdtdc/workers
Content-Type: application/json

{
    "id": "colab-1",
    "runtime_type": "cpu",
    "session_start": "2021-06-06T18:06:12",
    "session_duration": 86400.0,
    "endpoint": null
}


###
PUT http://1.117.72.139/XPJarvef6GxRdtdc/tasks/colab-main-1/log
Content-Type: application/json

{
    "content": "Fuck"
}